target: '最后一层加了dropout中间还是BN'
exp_name: 'net_model_Dropout'

device: 'cuda'

image_width: 1536
image_height: 1536
image_name: 'ref_pi_01_prop_pi'

seed: 1
batch_size: 1
lr: 0.0001
epochs: 80000

model:
  name: 'net_model_Dropout'



# # prop的默认参数
# dx = 2.2e-6
# dy = dx
# lam = 532e-9
dist: 0.01