target: '将网络里的卷积层进行了加深'
exp_name: 'net_model_Dropout_full'

device: 'cuda'

image_height: 1920
image_width: 1920

# image_name: 'ref_pi_01_prop_pi'

seed: 1
batch_size: 1
lr: 0.0001
epochs: 30000

model:
  name: 'net_model_Dropout_full'
  p: 0.01

folder_paths: [
        '/mnt/data/optimal/tangyuhang/workspace/iopen/ai4optical/phynet_git/traindata/pi/amp/baseline',
        '/mnt/data/optimal/tangyuhang/workspace/iopen/ai4optical/phynet_git/traindata/pi/amp/blood',
        '/mnt/data/optimal/tangyuhang/workspace/iopen/ai4optical/phynet_git/traindata/pi/amp/colon1',
        '/mnt/data/optimal/tangyuhang/workspace/iopen/ai4optical/phynet_git/traindata/pi/amp/colon2'
        ]

# # prop的默认参数
# dx = 2.2e-6
# dy = dx
# lam = 532e-9
dist: 0.01