target: '学习率的'
exp_name: 'ref_lr'

device: 'cuda'

image_width: 1536
image_height: 1536
image_name: 'ref_pi_01_prop_pi'

seed: 1
batch_size: 1

epochs: 30000

model:
  name: 'net_model_Dropout_full'



# # prop的默认参数
# dx = 2.2e-6
# dy = dx
# lam = 532e-9
dist: 0.01