target: '学习率的'
exp_name: 'net_model_depth_channel'

device: 'cuda'

image_width: 1536
image_height: 1536
image_name: 'ref_pi_01_prop_pi'

seed: 1
batch_size: 1
lr: 0.001
epochs: 30000

model:
  name: 'net_model_depth_channel'



# # prop的默认参数
# dx = 2.2e-6
# dy = dx
# lam = 532e-9
dist: 0.01