target: '将网络里的卷积层进行了加深'
exp_name: 'net_model_depth'

device: 'cuda'

image_width: 1536
image_height: 1536
image_name: 'sam_pi_01_prop_pi'

seed: 1
batch_size: 1
lr: 0.0001
epochs: 80000

model:
  name: 'net_model_depth'



# # prop的默认参数
# dx = 2.2e-6
# dy = dx
# lam = 532e-9
dist: 0.01
