target: 'defult'
device: 'cuda'

image_width: 1536
image_height: 1536
image_name: 'sam_pi_01_prop_pi'

seed: 1
batch_size: 1
lr: 0.0001
epochs: 80000

model:
  name: 'net_model_v1'



# # prop的默认参数
# dx = 2.2e-6
# dy = dx
# lam = 532e-9
dist: 0.01

data:
    train_path: 'data/train'
    test_path: 'test/train'
    num: 1000