target: ''
exp_name: 'test'

num: 10000
scale: '2pi'
dist: 0.04
core_radius: 5
image_height: 1920
image_width: 1920

constraint: 'strong'
# 'strong'
# 'weak'
#'strong'

# before_resize:
#   flag: False
#   size: 800

# after_resize:
#   flag: False
#   size: 1024

fi: 2
device: 'cuda'
seed: 1
batch_size: 1
lr: 0.0001
epochs: 11100
# model:
#   name: 'net_model_Dropout_full'
#   filename: 'net_model_Dropout_full'
#   classname: 'net_model_Dropout_full'
#   p: 0.01
model:
  name: 'U_Net'
  filename: 'model'
  classname: 'U_Net'
  # 'NestedUNet'
  #'U_Net'
  # p: 0.01
  # scale: '2pi'


loss:
  name: 'MSELoss'

loops: [10,100,1000,3000,10000,15000]

  # 'L1Loss'        
# # prop的默认参数
# dx = 2.2e-6
# dy = dx
# lam = 532e-9
